    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import com.polypro.dao.HocVienDAO;
import com.polypro.dao.NguoiHocDAO;
import com.polypro.helper.DialogHelper;
import com.polypro.helper.ShareHelper;
import com.polypro.helper.UHelper;
import com.polypro.helper.jdbcHelper;
import com.polypro.model.HocVien;
import com.polypro.model.NguoiHoc;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HocVienJFrame extends javax.swing.JFrame {

    public Integer MaKH;
    HocVienDAO dao = new HocVienDAO();
    NguoiHocDAO nhdao = new NguoiHocDAO();

    /**
     * Creates new form HocVienJFrame
     */
    public HocVienJFrame() {
        initComponents();
        init();
        this.MaKH = MaKH;
    }

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

    void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbx_nguoihoc.getModel();
        model.removeAllElements();
        try {
            List<NguoiHoc> list = nhdao.selectByCourse(MaKH);
            for (NguoiHoc nh : list) {
                model.addElement(nh);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn học viên!");
        }
    }

    void fillGridView() {
        DefaultTableModel model = (DefaultTableModel) tbl_bang.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT hv.*, nh.HoTen FROM HocVien hv "
                    + " JOIN NguoiHoc nh ON nh.MaNH=hv.MaNH WHERE MaKH=?";
            ResultSet rs = jdbcHelper.executeQuery(sql, MaKH);
            while (rs.next()) {
                double diem = rs.getDouble("Diem");
                Object[] row = {
                    rs.getInt("MaHV"), rs.getString("MaNH"),
                    rs.getString("HoTen"), diem, false
                };
                if (rdo_tatca.isSelected()) {
                    model.addRow(row);
                } else if (rdo_danhapdiem.isSelected() && diem >= 0) {
                    model.addRow(row);
                } else if (rdo_chuanhapdiem.isSelected() && diem < 0) {
                    model.addRow(row);
                }
            }
        } catch (SQLException e) {
            DialogHelper.alert(this, "Lỗi truy vấn học viên!");
        }
    }
     void insert() { 
        NguoiHoc nguoiHoc = (NguoiHoc) cbx_nguoihoc.getSelectedItem(); 
 
        HocVien model = new HocVien(); 
        model.setMaKH(MaKH); 
        model.setMaNH(nguoiHoc.getMaNH()); 
        model.setDiem(Double.valueOf(txt_diem.getText())); 
 
        try { 
            dao.insert(model); 
            this.fillComboBox(); 
            this.fillGridView(); 
        }  
        catch (Exception e) { 
            DialogHelper.alert(this, "Lỗi thêm học viên vào khóa học!"); 
        } 
    }
     void update(){
           for(int i=0;i<tbl_bang.getRowCount();i++){ 
            Integer mahv = (Integer) tbl_bang.getValueAt(i, 0); 
            String manh = (String) tbl_bang.getValueAt(i, 1); 
            Double diem = (Double) tbl_bang.getValueAt(i, 3); 
            Boolean isDelete = (Boolean) tbl_bang.getValueAt(i, 4); 
 
            if(isDelete){ 
                dao.delete(mahv); 
            } 
            else{        
                HocVien model = new HocVien(); 
                model.setMaHV(mahv); 
                model.setMaKH(MaKH); 
                model.setMaNH(manh); 
                model.setDiem(diem); 
 
                dao.update(model); 
            } 
        } 
        this.fillComboBox(); 
        this.fillGridView(); 
        DialogHelper.alert(this, "Cập nhật thành công!"); 
     }
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_hvtrongkhoa = new javax.swing.JLabel();
        pnl_hocvientrongcuakhoa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bang = new javax.swing.JTable();
        rdo_tatca = new javax.swing.JRadioButton();
        rdo_danhapdiem = new javax.swing.JRadioButton();
        rdo_chuanhapdiem = new javax.swing.JRadioButton();
        btn_update = new javax.swing.JButton();
        lbl_hvkhac = new javax.swing.JLabel();
        pnl_hocvienkhac = new javax.swing.JPanel();
        cbx_nguoihoc = new javax.swing.JComboBox();
        btn_them = new javax.swing.JButton();
        txt_diem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_hvtrongkhoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_hvtrongkhoa.setText("HỌC VIÊN TRONG CỦA KHÓA");

        pnl_hocvientrongcuakhoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ HV", "MÃ NH", "HỌ VÀ TÊN", "ĐIỂM", "XÓA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bang.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_bang);

        buttonGroup1.add(rdo_tatca);
        rdo_tatca.setSelected(true);
        rdo_tatca.setText("Tất cả");
        rdo_tatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_tatcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_danhapdiem);
        rdo_danhapdiem.setText("Đã nhập điểm");
        rdo_danhapdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_danhapdiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_chuanhapdiem);
        rdo_chuanhapdiem.setText("Chưa nhập điểm");
        rdo_chuanhapdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_chuanhapdiemActionPerformed(evt);
            }
        });

        btn_update.setText("Cập nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_hocvientrongcuakhoaLayout = new javax.swing.GroupLayout(pnl_hocvientrongcuakhoa);
        pnl_hocvientrongcuakhoa.setLayout(pnl_hocvientrongcuakhoaLayout);
        pnl_hocvientrongcuakhoaLayout.setHorizontalGroup(
            pnl_hocvientrongcuakhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hocvientrongcuakhoaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_hocvientrongcuakhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_hocvientrongcuakhoaLayout.createSequentialGroup()
                        .addComponent(rdo_tatca)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_danhapdiem)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_chuanhapdiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_hocvientrongcuakhoaLayout.setVerticalGroup(
            pnl_hocvientrongcuakhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hocvientrongcuakhoaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_hocvientrongcuakhoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_tatca)
                    .addComponent(rdo_danhapdiem)
                    .addComponent(rdo_chuanhapdiem)
                    .addComponent(btn_update))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_hvkhac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_hvkhac.setText("HỌC VIÊN KHÁC");

        pnl_hocvienkhac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbx_nguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nguoihocActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_hocvienkhacLayout = new javax.swing.GroupLayout(pnl_hocvienkhac);
        pnl_hocvienkhac.setLayout(pnl_hocvienkhacLayout);
        pnl_hocvienkhacLayout.setHorizontalGroup(
            pnl_hocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hocvienkhacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbx_nguoihoc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_diem)
                .addGap(18, 18, 18)
                .addComponent(btn_them)
                .addContainerGap())
        );
        pnl_hocvienkhacLayout.setVerticalGroup(
            pnl_hocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hocvienkhacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_hocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_nguoihoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them)
                    .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_hocvienkhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_hocvientrongcuakhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_hvkhac)
                            .addComponent(lbl_hvtrongkhoa))
                        .addGap(0, 353, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_hvkhac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_hocvienkhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_hvtrongkhoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_hocvientrongcuakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if(!UHelper.checkNull_JTextField(txt_diem, "Điểm ")){
        return;
    }
        if(!UHelper.checkDiem_JTextField(txt_diem, " Điểm")){
            return;
        }
        this.insert();
    }//GEN-LAST:event_btn_themActionPerformed

    private void rdo_danhapdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_danhapdiemActionPerformed
        // TODO add your handling code here:
        this.fillGridView();
        
    }//GEN-LAST:event_rdo_danhapdiemActionPerformed

    private void rdo_tatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_tatcaActionPerformed
        // TODO add your handling code here:
        this.fillGridView();
    }//GEN-LAST:event_rdo_tatcaActionPerformed

    private void rdo_chuanhapdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_chuanhapdiemActionPerformed
        // TODO add your handling code here:
        this.fillGridView();
    }//GEN-LAST:event_rdo_chuanhapdiemActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cbx_nguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nguoihocActionPerformed
        // TODO add your handling code here:
        this.fillComboBox();
    }//GEN-LAST:event_cbx_nguoihocActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.fillComboBox();
        this.fillGridView();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbx_nguoihoc;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_hvkhac;
    private javax.swing.JLabel lbl_hvtrongkhoa;
    private javax.swing.JPanel pnl_hocvienkhac;
    private javax.swing.JPanel pnl_hocvientrongcuakhoa;
    private javax.swing.JRadioButton rdo_chuanhapdiem;
    private javax.swing.JRadioButton rdo_danhapdiem;
    private javax.swing.JRadioButton rdo_tatca;
    private javax.swing.JTable tbl_bang;
    private javax.swing.JTextField txt_diem;
    // End of variables declaration//GEN-END:variables
}
