/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import com.polypro.dao.KhoaHocDAO;
import com.polypro.dao.ThongKeDAO;
import com.polypro.helper.ShareHelper;
import com.polypro.model.KhoaHoc;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeJInternalFrame extends javax.swing.JInternalFrame {

    ThongKeDAO dao = new ThongKeDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();

    /**
     * Creates new form ThongKeJInternalFrame
     */
    public ThongKeJInternalFrame() {
        initComponents();
        init();
        tabs.setSelectedIndex(0); 
    }

    void init() {
        setFrameIcon(ShareHelper.APP_ICON_1);
    }

    void fillComboBoxKhoaHoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbx_khoahoc.getModel();
        model.removeAllElements();

        List<KhoaHoc> list = khdao.select();
        for (KhoaHoc kh : list) {
            model.addElement(kh);
        }

        cbx_khoahoc.setSelectedIndex(0);
    }

    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbx_nam1.getModel();
        model.removeAllElements();

        List<KhoaHoc> list = khdao.select();
        for (KhoaHoc kh : list) {
            int nam = kh.getNgayKG().getYear() + 1900;
            if (model.getIndexOf(nam) < 0) {
                model.addElement(nam);
            }
        }

        cbx_nam1.setSelectedIndex(0);
    }

    void fillTableBangDiem() {
        DefaultTableModel model = (DefaultTableModel) tbl_bangdiem.getModel();
        model.setRowCount(0);

        KhoaHoc kh = (KhoaHoc) cbx_khoahoc.getSelectedItem();
        List<Object[]> list = dao.getBangDiem(kh.getMaKH());
        for (Object[] row : list) {
            model.addRow(row);
        }

    }

    void fillTableNguoiHoc() {
        DefaultTableModel model = (DefaultTableModel) tbl_nguoihoc.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getNguoiHoc();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableKhoaHoc() {
        DefaultTableModel model = (DefaultTableModel) tbl_tonghop.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getDiemTheoChuyenDe();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tbl_doanhthu.getModel();
        model.setRowCount(0);
        int nam = Integer.parseInt(cbx_nam1.getSelectedItem().toString());
        List<Object[]> list = dao.getDoanhThu(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_nguoihoc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nguoihoc = new javax.swing.JTable();
        pnl_bangdiem = new javax.swing.JPanel();
        pnl_khoahoc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbx_khoahoc = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bangdiem = new javax.swing.JTable();
        lbl_tonghopdiem = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_tonghop = new javax.swing.JTable();
        lbl_doanhthu = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_doanhthu = new javax.swing.JTable();
        pnl_name = new javax.swing.JPanel();
        lbl_nam = new javax.swing.JLabel();
        cbx_nam1 = new javax.swing.JComboBox();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(0, 0, 204));
        lbl_title.setText("TỔNG HỢP THỐNG KÊ");

        pnl_nguoihoc.setLayout(new java.awt.BorderLayout());

        tbl_nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NĂM", "SỐ NGƯỜI HỌC", "ĐẦU TIÊN", "SAU CÙNG"
            }
        ));
        tbl_nguoihoc.setRowHeight(25);
        jScrollPane1.setViewportView(tbl_nguoihoc);

        pnl_nguoihoc.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabs.addTab("NGƯỜI HỌC", pnl_nguoihoc);

        pnl_bangdiem.setLayout(new java.awt.BorderLayout());

        pnl_khoahoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_khoahoc.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("KHÓA HỌC:");
        pnl_khoahoc.add(jLabel1, java.awt.BorderLayout.LINE_START);

        cbx_khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_khoahocActionPerformed(evt);
            }
        });
        pnl_khoahoc.add(cbx_khoahoc, java.awt.BorderLayout.CENTER);

        pnl_bangdiem.add(pnl_khoahoc, java.awt.BorderLayout.PAGE_START);

        tbl_bangdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NH", "HỌ VÀ TÊN", "ĐIỂM", "XẾP LOẠI"
            }
        ));
        tbl_bangdiem.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_bangdiem);

        pnl_bangdiem.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tabs.addTab("BẢNG ĐIỂM", pnl_bangdiem);

        lbl_tonghopdiem.setLayout(new java.awt.BorderLayout());

        tbl_tonghop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CHUYÊN ĐỀ", "TỔNG SỐ HV", "CAO NHẤT", "THẤP NHẤT", "ĐIỂM TB"
            }
        ));
        tbl_tonghop.setRowHeight(25);
        jScrollPane3.setViewportView(tbl_tonghop);

        lbl_tonghopdiem.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabs.addTab("TỔNG HỢP ĐIỂM", lbl_tonghopdiem);

        lbl_doanhthu.setLayout(new java.awt.BorderLayout());

        tbl_doanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CHUYÊN ĐỀ", "SỐ KHÓA", "SỐ HV", "DOANH THU", "HP CAO NHẤT", "HP THẤP NHẤT", "HP TRUNG BÌNH"
            }
        ));
        tbl_doanhthu.setRowHeight(25);
        jScrollPane4.setViewportView(tbl_doanhthu);

        lbl_doanhthu.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pnl_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_name.setLayout(new java.awt.BorderLayout());

        lbl_nam.setText("NĂM:");
        pnl_name.add(lbl_nam, java.awt.BorderLayout.LINE_START);

        cbx_nam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nam1ActionPerformed(evt);
            }
        });
        pnl_name.add(cbx_nam1, java.awt.BorderLayout.CENTER);

        lbl_doanhthu.add(pnl_name, java.awt.BorderLayout.PAGE_START);

        tabs.addTab("DOANH THU", lbl_doanhthu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_nam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nam1ActionPerformed
        // TODO add your handling code here:
        this.fillTableDoanhThu();
    }//GEN-LAST:event_cbx_nam1ActionPerformed

    private void cbx_khoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_khoahocActionPerformed
        // TODO add your handling code here:
        this.fillTableBangDiem();
    }//GEN-LAST:event_cbx_khoahocActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        this.fillComboBoxKhoaHoc();
        this.fillTableBangDiem();
        this.fillTableNguoiHoc();
        this.fillTableKhoaHoc();
        this.fillComboBoxNam();
        this.fillTableDoanhThu();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbx_khoahoc;
    private javax.swing.JComboBox cbx_nam1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel lbl_doanhthu;
    private javax.swing.JLabel lbl_nam;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel lbl_tonghopdiem;
    private javax.swing.JPanel pnl_bangdiem;
    private javax.swing.JPanel pnl_khoahoc;
    private javax.swing.JPanel pnl_name;
    private javax.swing.JPanel pnl_nguoihoc;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_bangdiem;
    private javax.swing.JTable tbl_doanhthu;
    private javax.swing.JTable tbl_nguoihoc;
    private javax.swing.JTable tbl_tonghop;
    // End of variables declaration//GEN-END:variables
}
